import DashboardPage from "@/components/Pages/DashboardPage";
import Head from "next/head";

export default function Dashboard() {
    return (
        <>
            <Head>
                <title>UnivKensen | Dashboard</title>
                <meta name="description" content="Generated by Create Next Stack." />

            </Head>
            <DashboardPage  />
        </>
    )
}
