import DashboardPage from "@/components/Pages/DashboardPage";
import InputNilaiPage from "@/components/Pages/InputNilaiPage";
import Head from "next/head";

export default function InputNilai() {
    return (
        <>
            <Head>
                <title>UnivKensen | Input Nilai</title>
                <meta name="description" content="Generated by Create Next Stack." />

            </Head>
            <InputNilaiPage/>
        </>
    )
}
