import LoginPage from "@/components/Pages/LoginPage";
import Head from "next/head";

export default function InputNilai() {
    return (
        <>
            <Head>
                <title>UnivKensen | Input Nilai</title>
                <meta name="description" content="Generated by Create Next Stack." />

            </Head>
            <LoginPage />
        </>
    )
}
