import DashboardPage from "@/components/Pages/DashboardPage";
import InputNilaiPage from "@/components/Pages/InputNilaiPage";
import ProfilPage from "@/components/Pages/ProfilPage";
import Head from "next/head";

export default function Profil() {
  return (
    <>
      <Head>
        <title>UnivKensen | Input Nilai</title>
        <meta name="description" content="Generated by Create Next Stack." />

      </Head>
      <ProfilPage />
    </>
  )
}
