import DashboardPage from "@/components/Pages/DashboardPage";
import InputNilaiPage from "@/components/Pages/InputNilaiPage";
import TabelNilaiPage from "@/components/Pages/TabelNilai";
import Head from "next/head";

export default function TabelNilai() {
  return (
    <>
      <Head>
        <title>UnivKensen | Input Nilai</title>
        <meta name="description" content="Generated by Create Next Stack." />

      </Head>
      <TabelNilaiPage />
    </>
  )
}
